spring.application.name=ecommerce-search-api

server.port=8080

elasticsearch.url=http://localhost:9200
elasticsearch.index=products

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
